### ISSUE TITLE
Perf improvements and cleanups

### ISSUE THREAD

**Issue by ftonato** [GSA/code-gov-front-end#132]
Hello,

I was reading the code so I saw opportunities for some simple improvements/cleanups...

- I removed unused imports and variables;
- I changed some `else` unnecessaries;
- I changed some `let` variables to `const` because they are not rewritten.

**Feels comfortable to discard any change I made...**

> _Happy Christmas_

**Comment by ftonato** [comment]
Hello @saracope,

After you fixed the merge (tks for that), I created a new pull-request of `ftonato-add-improvments` to `master` as expected, but occurred a new issue to fix (codeclimate), so I have created a new pr of `ftonato-feature-improvements-fix` to `ftonato-feature-improvements`...

----

We need to follow this order to solve them:

- [ ] Accept the pr #250
- [ ] Accept the pr #249 (Original improvements with merge fixed)
  - [ ] This will automatic close the issue #132
- [ ] Close the out of date pr #133
