### ISSUE TITLE
Home redesign - rewriting

### ISSUE THREAD

**Issue by ftonato** [GSA/code-gov-front-end#251]
Hello nerds, how are you? :nerd_face:

After the update #240 - I noticed some styles written in a way not so "interesting" and as I had a free-time, I decided to send some small pull-requests to try to bring benefit to the project.

**Please, keep this issue opening as long as I don't finish the below list of pull-requests**

----
### Pull-requests

- [x] Search form (#252 - **Close**)
- [x] Footer can be a Pure Component (#253 - **Merged**)
- [x] Zero absolute is zero (#254 - **Merged**)
- [ ] Footer style/"semantic sense" (#255 - Waiting for approval)

#### Note
**If you accept the pull-requests in order, we'll need a merge between #253 and #255 pull-request file, but it's simple to solve ;)**

**Comment by ftonato** [comment]
I finally finalized, after you reviewing everything, can accept, and then we closed the issue...

Please, don't forget this one - https://github.com/GSA/code-gov-style/pull/92
